version: 2.1

orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: openjdk:8-jdk
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
      TERM: dumb
    steps:
      - checkout
      
      - run: chmod +x gradlew
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "lib/build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
          
      # run tests!
      - run: ./gradlew clean check jacocoTestReport --continue --console=plain
      
      - codecov/upload
      
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "lib/build.gradle" }}
workflows:
  build-and-test:
    jobs:
      - build
